openapi: 3.0.3
info:
  title: Artwork API
  description: HTTP API for managing image graphs and their processing pipelines
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /imagegraphs:
    post:
      summary: Create a new ImageGraph
      description: Creates a new ImageGraph with the specified name
      operationId: createImageGraph
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: The name of the ImageGraph
                  example: "My Image Pipeline"
      responses:
        '201':
          description: ImageGraph created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: The unique identifier of the created ImageGraph
                    example: "550e8400-e29b-41d4-a716-446655440000"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "name is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to create image graph"

  /imagegraphs/{id}:
    get:
      summary: Get an ImageGraph by ID
      description: Retrieves an ImageGraph with all its nodes
      operationId: getImageGraph
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: ImageGraph retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: The unique identifier of the ImageGraph
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  name:
                    type: string
                    description: The name of the ImageGraph
                    example: "My Image Pipeline"
                  version:
                    type: integer
                    description: The version number of the ImageGraph
                    example: 5
                  nodes:
                    type: array
                    description: The nodes in the ImageGraph
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: The unique identifier of the node
                          example: "660e8400-e29b-41d4-a716-446655440001"
                        name:
                          type: string
                          description: The name of the node
                          example: "Input Node"
                        type:
                          type: string
                          description: The type of the node
                          example: "input"
                        version:
                          type: integer
                          description: The version number of the node
                          example: 3
                        config:
                          type: string
                          description: JSON configuration for the node
                          example: "{}"
        '400':
          description: Bad request - invalid UUID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "invalid image graph ID"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to retrieve image graph"

  /imagegraphs/{id}/nodes:
    post:
      summary: Add a node to an ImageGraph
      description: Creates a new node in the specified ImageGraph
      operationId: addNode
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - type
                - config
              properties:
                name:
                  type: string
                  description: The name of the node
                  example: "My Input Node"
                type:
                  type: string
                  description: The type of the node
                  example: "input"
                  enum: [input, scale]
                config:
                  type: string
                  description: JSON configuration for the node
                  example: "{}"
      responses:
        '201':
          description: Node created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: The unique identifier of the created node
                    example: "660e8400-e29b-41d4-a716-446655440001"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "name is required"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to add node"

  /imagegraphs/{id}/nodes/{node_id}:
    delete:
      summary: Delete a node from an ImageGraph
      description: Removes the specified node from the ImageGraph
      operationId: deleteNode
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: node_id
          in: path
          required: true
          description: The unique identifier of the node to delete
          schema:
            type: string
            format: uuid
            example: "660e8400-e29b-41d4-a716-446655440001"
      responses:
        '204':
          description: Node deleted successfully (no content)
        '400':
          description: Bad request - invalid UUID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "invalid image graph ID"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to delete node"

  /imagegraphs/{id}/connectNodes:
    put:
      summary: Connect two nodes in an ImageGraph
      description: Creates a connection from one node's output to another node's input
      operationId: connectNodes
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - from_node_id
                - output_name
                - to_node_id
                - input_name
              properties:
                from_node_id:
                  type: string
                  format: uuid
                  description: The node providing the output
                  example: "660e8400-e29b-41d4-a716-446655440001"
                output_name:
                  type: string
                  description: The name of the output on the source node
                  example: "output"
                to_node_id:
                  type: string
                  format: uuid
                  description: The node receiving the input
                  example: "770e8400-e29b-41d4-a716-446655440002"
                input_name:
                  type: string
                  description: The name of the input on the target node
                  example: "input"
      responses:
        '204':
          description: Nodes connected successfully (no content)
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "from_node_id is required"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to connect nodes"

  /imagegraphs/{id}/disconnectNodes:
    put:
      summary: Disconnect two nodes in an ImageGraph
      description: Removes a connection from one node's output to another node's input
      operationId: disconnectNodes
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - from_node_id
                - output_name
                - to_node_id
                - input_name
              properties:
                from_node_id:
                  type: string
                  format: uuid
                  description: The node providing the output
                  example: "660e8400-e29b-41d4-a716-446655440001"
                output_name:
                  type: string
                  description: The name of the output on the source node
                  example: "output"
                to_node_id:
                  type: string
                  format: uuid
                  description: The node receiving the input
                  example: "770e8400-e29b-41d4-a716-446655440002"
                input_name:
                  type: string
                  description: The name of the input on the target node
                  example: "input"
      responses:
        '204':
          description: Nodes disconnected successfully (no content)
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "from_node_id is required"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to disconnect nodes"

  /imagegraphs/{id}/nodes/{node_id}/config:
    patch:
      summary: Update a node's configuration
      description: Sets the configuration for a specific node in the ImageGraph
      operationId: setNodeConfig
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: node_id
          in: path
          required: true
          description: The unique identifier of the node
          schema:
            type: string
            format: uuid
            example: "660e8400-e29b-41d4-a716-446655440001"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - config
              properties:
                config:
                  type: string
                  description: JSON configuration for the node
                  example: "{\"path\": \"/some/path\"}"
      responses:
        '204':
          description: Node config updated successfully (no content)
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "config is required"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to set node config"

  /imagegraphs/{id}/nodes/{node_id}/outputs/{output_name}:
    patch:
      summary: Set a node's output image
      description: Sets the image ID for a specific output of a node
      operationId: setNodeOutputImage
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the ImageGraph
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
        - name: node_id
          in: path
          required: true
          description: The unique identifier of the node
          schema:
            type: string
            format: uuid
            example: "660e8400-e29b-41d4-a716-446655440001"
        - name: output_name
          in: path
          required: true
          description: The name of the output
          schema:
            type: string
            example: "output"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - image_id
              properties:
                image_id:
                  type: string
                  format: uuid
                  description: The unique identifier of the image
                  example: "770e8400-e29b-41d4-a716-446655440003"
      responses:
        '204':
          description: Output image set successfully (no content)
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image_id is required"
        '404':
          description: ImageGraph not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "image graph not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to set node output image"
